---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote-user: root
  gather_facts: False

  tasks:

    - name: Handle servicegroup
      delegate_to_ localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        maxclient: "10"
        autoscale: API
        servicemembers:
          mode: dsapi
          attributes:
            - ip: 10.1.30.1
              port: 80
            - ip: 10.1.30.2
              port: 80

 